# Generated by Django 5.2.17 on 2026-10-03 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notify_emails', models.TextField(blank=True, help_text='Comma-separated addresses that get new-enquiry emails. Empty uses ENQUIRY_NOTIFY_EMAIL.')),
                ('analytics_retention_days', models.PositiveIntegerField(default=395)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'dashboard settings',
                'verbose_name_plural': 'dashboard settings',
            },
        ),
        migrations.CreateModel(
            name='LoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('area', models.CharField(choices=[('dashboard', 'Dashboard'), ('django-admin', 'Django admin')], max_length=15)),
                ('outcome', models.CharField(choices=[('success', 'Success'), ('failed', 'Wrong username or password'), ('blocked', 'Blocked (too many attempts)'), ('not-staff', 'Not an admin account')], max_length=10)),
                ('username', models.CharField(blank=True, max_length=150)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=2)),
                ('city', models.CharField(blank=True, max_length=80)),
                ('user_agent', models.CharField(blank=True, max_length=300)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VisitEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('kind', models.CharField(choices=[('pageview', 'Page view'), ('event', 'Event')], default='pageview', max_length=10)),
                ('name', models.CharField(blank=True, max_length=40)),
                ('label', models.CharField(blank=True, max_length=80)),
                ('visitor', models.CharField(db_index=True, max_length=32)),
                ('path', models.CharField(default='/', max_length=200)),
                ('channel', models.CharField(blank=True, db_index=True, max_length=20)),
                ('source', models.CharField(blank=True, max_length=80)),
                ('referrer_host', models.CharField(blank=True, max_length=120)),
                ('utm_source', models.CharField(blank=True, max_length=80)),
                ('utm_medium', models.CharField(blank=True, max_length=80)),
                ('utm_campaign', models.CharField(blank=True, max_length=120)),
                ('country', models.CharField(blank=True, max_length=2)),
                ('region', models.CharField(blank=True, max_length=80)),
                ('city', models.CharField(blank=True, max_length=80)),
                ('device', models.CharField(blank=True, max_length=10)),
                ('browser', models.CharField(blank=True, max_length=20)),
                ('os', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
