# Generated by Django 5.2.17 on 2026-10-03 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='channel',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='city',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='country',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='source',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='utm_campaign',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
