# Generated by Django 5.2.17 on 2026-10-03 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0002_enquiry_channel_enquiry_city_enquiry_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
